import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:google_mobile_ads/google_mobile_ads.dart';

import 'firebase_options.dart';
import 'providers/auth_provider.dart';
import 'providers/team_provider.dart';
import 'providers/game_provider.dart';
import 'providers/chat_provider.dart';
import 'providers/user_provider.dart';
import 'providers/report_provider.dart';
import 'screens/splash_screen.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  String? firebaseInitError;

  try {
    // Initialize Firebase with explicit options generated by FlutterFire.
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    debugPrint('✅ Firebase initialized successfully');
  } on FirebaseException catch (e, st) {
    // If the default app is already configured on the native side,
    // Firebase throws a "duplicate-app" error. In that case it's safe
    // to continue as Firebase is already ready to use.
    if (e.code == 'duplicate-app') {
      debugPrint(
        '⚠️ Firebase default app already exists; '
        'continuing without re-initializing.',
      );
    } else {
      firebaseInitError = e.toString();
      debugPrint('❌ Firebase initialization error: $e');
      debugPrint(st.toString());
    }
  } catch (e, st) {
    firebaseInitError = e.toString();
    debugPrint('❌ Firebase initialization error: $e');
    debugPrint(st.toString());
  }

  try {
    await MobileAds.instance.initialize();
    debugPrint('✅ Mobile Ads initialized successfully');
  } catch (e) {
    debugPrint('❌ Mobile Ads initialization error: $e');
  }

  runApp(RosterUpApp(firebaseInitError: firebaseInitError));
}

class RosterUpApp extends StatelessWidget {
  const RosterUpApp({super.key, this.firebaseInitError});

  final String? firebaseInitError;

  @override
  Widget build(BuildContext context) {
    if (firebaseInitError != null) {
      // Surface initialization problems instead of a blank screen.
      return MaterialApp(
        debugShowCheckedModeBanner: false,
        home: Scaffold(
          appBar: AppBar(title: const Text('Firebase error')),
          body: Padding(
            padding: const EdgeInsets.all(16),
            child: SingleChildScrollView(
              child: Text(
                'Firebase failed to initialize:\n\n$firebaseInitError',
                style: const TextStyle(fontSize: 16),
              ),
            ),
          ),
        ),
      );
    }

    const seed = Color(0xFF0056D6); // sporty deep blue

    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthProvider()),
        ChangeNotifierProvider(create: (_) => UserProvider()),
        ChangeNotifierProvider(create: (_) => TeamProvider()),
        ChangeNotifierProvider(create: (_) => GameProvider()),
        ChangeNotifierProvider(create: (_) => ChatProvider()),
        ChangeNotifierProvider(create: (_) => ReportProvider()),
      ],
      child: Consumer<UserProvider>(
        builder: (context, userProvider, _) {
          final prefs = userProvider.currentUser?.preferences ?? {};
          final themePref = prefs['theme'] as String? ?? 'light';

          ThemeMode themeMode;
          switch (themePref) {
            case 'dark':
              themeMode = ThemeMode.dark;
              break;
            default:
              // Default to light mode if no preference or an old
              // "system" value is stored.
              themeMode = ThemeMode.light;
          }

          return MaterialApp(
            debugShowCheckedModeBanner: false,
            title: 'RosterUp',
            theme: ThemeData(
              useMaterial3: true,
              colorScheme: ColorScheme.fromSeed(
                seedColor: seed,
                brightness: Brightness.light,
              ),
              appBarTheme: const AppBarTheme(centerTitle: true),
            ),
            darkTheme: ThemeData(
              useMaterial3: true,
              colorScheme: ColorScheme.fromSeed(
                seedColor: seed,
                brightness: Brightness.dark,
              ),
              appBarTheme: const AppBarTheme(centerTitle: true),
            ),
            themeMode: themeMode,
            home: const SplashScreen(),
          );
        },
      ),
    );
  }
}
